name: radioapps
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audio_session: ^0.1.14
  rxdart: ^0.27.2

  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - path: "assets/flavors/hfm"
      flavors:
        - hfm
    - path: "assets/flavors/greatdriffield"
      flavors:
        - greatdriffield
