name: radioapps
description: "Radioapps base project"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # make http calls to a service
  http: ^1.2.1


  audio_session: ^0.1.14
  rxdart: ^0.27.2
  # bloc state management
  flutter_bloc: ^8.1.3

  # this is an improved color scheme seed code
  flex_seed_scheme: ^1.4.0

  # flexible font loading - note import the fonts into project before release
  google_fonts: ^6.1.0

  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11

  shared_preferences: ^2.2.2

  # used to display the news feed
  webview_flutter: ^4.7.0

  # allows links to be opened (phone numbers, websites etc)
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/
    - path: assets/flavors/hfm/
      flavors:
        - hfm
    - path: assets/flavors/greatdriffield/
      flavors:
        - greatdriffield
